// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StrucnaPraksa.Models;

namespace StrucnaPraksa.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200127194857_osnovniPodaci")]
    partial class osnovniPodaci
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StrucnaPraksa.Entities.OsnovniPodaci", b =>
                {
                    b.Property<string>("IdUsera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazivMentora")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poduzece")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Termin")
                        .HasColumnType("datetime2");

                    b.ToTable("OsnovniPodaci");
                });

            modelBuilder.Entity("StrucnaPraksa.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "admin",
                            Role = "Admin",
                            Username = "fabijan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
