// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StrucnaPraksa.Models;

namespace StrucnaPraksa.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StrucnaPraksa.Entities.Anketa", b =>
                {
                    b.Property<string>("IdAnkete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Cetvrto")
                        .HasColumnType("int");

                    b.Property<string>("Deseto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesetoKomentar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Deveto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Drugo")
                        .HasColumnType("int");

                    b.Property<string>("Dvanaesto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Godina")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUsera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jedanaesto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Osmo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Peto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prvo")
                        .HasColumnType("int");

                    b.Property<string>("Sedmo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SedmoKomentar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sesto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Trece")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAnkete");

                    b.ToTable("Ankete");
                });

            modelBuilder.Entity("StrucnaPraksa.Entities.Dnevnik", b =>
                {
                    b.Property<string>("IdDnevnika")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Godina")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUsera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDnevnika");

                    b.ToTable("Dnevnici");
                });

            modelBuilder.Entity("StrucnaPraksa.Entities.Izvjesce", b =>
                {
                    b.Property<string>("IdIzvjesca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Godina")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUsera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdIzvjesca");

                    b.ToTable("Izvjesca");
                });

            modelBuilder.Entity("StrucnaPraksa.Entities.OsnovniPodaci", b =>
                {
                    b.Property<string>("IdPodataka")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdUsera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NazivMentora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poduzece")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Termin")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("studij")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPodataka");

                    b.ToTable("OsnovniPodaci");
                });

            modelBuilder.Entity("StrucnaPraksa.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ime = "Fabijan",
                            Password = "admin",
                            Prezime = "Zulj",
                            Role = "Admin",
                            Username = "fabijan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
